### ISSUE TITLE
Layered Navigation

### ISSUE THREAD

**Issue by michielfb** [EmicoEcommerce/Magento2Tweakwise-archived#1]
Issue Brief
--
Layered navigation is not updated after installing Tweakwise. 

Environment
--
Magento Version: 2.1.5 CE
Tweakwise Version: 1.0.0
Tweakwise Export Version: 1.0.0
Environment: development
Third party modules: None, clean Magento 2 install

Steps to reproduce
--
1. Install Tweakwise extensions.
2. Setup Tweakwise and run import/export scripts
3. Flush caches
4. Go a category page

Actual result
--
Layered navigation is still the plain Magento

Expected result
--
Layered navigation and result should be updated by Tweakwise

**Comment by Fgruntjes** [comment]
The extension is disabled by default. You would first need to enable the extension in the configuration. This is done under Configuration -> Catalog -> Tweakwise. If this does not work out please reopen the issue.

Ill update the readme accordingly.
