### ISSUE TITLE
Search: displayed searchresults is stuck

### ISSUE THREAD

**Issue by mediactbv** [EmicoEcommerce/Magento2Tweakwise-archived#10]
When using the search, the displayed searchresults will appear > this is fine.
When you click random on a empty space you expect the displayed searchresults to close.
This does not happen which makes you unable to browse properly.

**Environment**

- PHP Version: 70
- Magento Version: 2.1.7
- Tweakwise Version: 1.0.1
- Tweakwise Export Version: 1.0.2
- Magento Deploy Mode: production

Steps to reproduce

1. enter a search term with results, the autocomplete will appear with search results
2. try to close the window, this can only be done by pressing ESC

Actual result

1. by clicking outside the search dropdown the searchdropdown will not close

Expected result

1. by clicking outside the search dropdown the searchdropdown should close

**Comment by Fgruntjes** [comment]
The search module is using the default magento autocomplete search. See also src/view/frontend/web/form-mini.js. We have tested this and it is working as expected on the default theme.
