### ISSUE TITLE
No configuration fields are visible in the Tweakwise system configuration of Magento.

### ISSUE THREAD

**Issue by igorwulff** [EmicoEcommerce/Magento2Tweakwise-archived#101]
Issue Brief
--
No configuration fields are visible in the Tweakwise system configuration of Magento.

Environment
--
* PHP Version: 7.3
* Magento Version: 2.3.3
* Tweakwise Version: v2.1.6
* Magento Deploy Mode: production

Steps to reproduce
Remove all entries for Tweakwise from the core_config_data and flush the config cache.

Actual result
When you try to go to the system configuration for Tweakwise you see a white area where the Tweakwise tabs and fields should be.

Expected result
Have the configuration fields for Tweakwise appear in the system configuration:

Logs:
system.log: [2020-01-29 14:51:09] report.CRITICAL: Invalid response received by Tweakwise server, response code is not 200. Request "http://navigator-group1.tweakwise.com/catalog/languages/"

**Comment by edwinljacobs** [comment]
Hello,

Commit: https://github.com/EmicoEcommerce/Magento2Tweakwise/pull/98/commits/092bda1b204d38e9c6a098a968f55b053b69a0c5 should fix that issue. Apparently it doesn't, could you add a stack trace for reference?

With kind regards

**Comment by edwinljacobs** [comment]
Hi,

I cannot reproduce the issue, I tried the following:
composer install --prefer-source
cd vendor/emico/tweakwise && git checkout v2.1.6
execute ```DELETE FROM core_config_data WHERE path LIKE 'tweakwise/%'```
bin/magento cache:flush 
reload configuration > catalog > tweakwise.

I get the expected configuration options, I do get the log messages however this is expected.

**Comment by edwinljacobs** [comment]
I updated my installation to 2.3.3 to be sure. I dont have this issue.
Could you add a trace?

**Comment by edwinljacobs** [comment]
Is this still an issue?

**Comment by edwinljacobs** [comment]
Closed due to inactivity
