### ISSUE TITLE
Double slash in URL after filtering

### ISSUE THREAD

**Issue by Alex-MaxServ** [EmicoEcommerce/Magento2Tweakwise-archived#104]
Issue Brief
--
Within our current project we ensure that every non product-detail page ends with a slash /. After filtering, the new url contains a double slash.

Environment
--
PHP Version: 7.1
Magento Version: 2.2.10
Tweakwise Version: 2.1.5
Tweakwise Export Version: 1.5.0
Magento Deploy Mode: development

Steps to reproduce
--

1. Ensure URL's of listingpages, category pages ends with /
2. Select filter

Actual result
--
domainname.com/category//filtername/filtervalue

Expected result
--
domainname.com/category/filtername/filtervalue

**Comment by edwinljacobs** [comment]
What exactly do you mean with "Ensure URL's of listing pages"?

**Comment by Alex-MaxServ** [comment]
Ensure that all url's will end with a trailing slash, in our case except the product detail pages.
domain.com/category/ 
domain.com/category/subcategory/

**Comment by edwinljacobs** [comment]
Ok but is this some sort of setting in magento or is this custom code in your project?

**Comment by Alex-MaxServ** [comment]
In Magento2 we use the option "Category URL Suffix". This is a standard feature.
![image](https://user-images.githubusercontent.com/52274863/73840701-009ea280-4819-11ea-88b6-3db91ec65d38.png)

**Comment by edwinljacobs** [comment]
Hello,

We made branch: issue/104-double-slash-in-url-when-suffix-is-slash. The issue should be fixed here.

Could you verify if these changes resolve your issue?

**Comment by Alex-MaxServ** [comment]
Hi Edwin,
As far as I can test and see, this branch works fine! Thank you

**Comment by edwinljacobs** [comment]
Hello,

This has been fixed in https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v2.1.7

With kind regards
