### ISSUE TITLE
Show X more - Placeholder always shows "1"

### ISSUE THREAD

**Issue by jkekkel** [EmicoEcommerce/Magento2Tweakwise-archived#111]
Issue Brief
--
In our filtertemplate we often show only 5 items for one filter. After that you get the option to expand and view the other options. We wanted to use the placeholder that shows the number of options that you can view if you expand the filter. Unfortunately this placeholder always shows the number 1. No matter how many values there are.

Environment
--
PHP Version: 7.1
Magento Version: 2.2.10
Tweakwise Version: 2.1.5
Tweakwise Export Version: 1.5.0
Magento Deploy Mode: development

Steps to reproduce
--
1. Use the placeholder for the "show more" option 

Actual result
--
1. The filtertemplate shows on the frontend "Show 1 more" no matter how many values there are

Expected result
--
- [] The placeholder shows the right amount of available values under the show more option. So if there are 8 more values it shows "Show 8 more".

**Comment by edwinljacobs** [comment]
Hi this has been added to the backlog, we will look into it.

**Comment by edwinljacobs** [comment]
Hi,

I am not entirely sure on what you mean. As I read it I thought it would be about the show more / show less filters button (see image 'Meer tonen')
![show-more](https://user-images.githubusercontent.com/11278380/76982213-da9e0f00-693b-11ea-907d-b2f0a1d8290f.png)

As far as I am aware, this text is configurable in the filter settings of the corresponding filtertemplate in tweakwise (go to your template > select the filter > advanced and there you find 'Show more' text and 'Show less' text). I see no way to add a placeholder there. The tweakwise module reads these values and outputs that as the text for the show more button. 

I problably misunderstood your issue, if so, can you clarify what goes wrong? Perhaps I misunderstand what you mean by Use the placeholder for the "show more" option?

With kind regards, Edwin Jacobs

**Comment by edwinljacobs** [comment]
Is this still relevant?

**Comment by jkekkel** [comment]
Hi Edwin,
This is still relevant. I just got this back from our partner: 
![image](https://user-images.githubusercontent.com/60736470/78361625-fe5a8980-75b8-11ea-94d0-913e0bd74850.png)

Can you do anything with this information? Or do you need something more specific?

**Comment by jkekkel** [comment]
I just heard from Maxserv that this was apparently something they actually did do themselves and that we didn't use any placeholders from you. Sorry for the inconvenience.
