### ISSUE TITLE
Exponential values resulting in bad exports

### ISSUE THREAD

**Issue by kozie** [EmicoEcommerce/Magento2Tweakwise-archived#112]
Issue Brief
--
Since Magento 2.3.4 the have increased the value size of `catalog_product_entity_decimal`. This way you can enter values like `999999999999999.99900` in which the max was previously `99999999999.99900` in an earlier version of Magento.
The latter value was display as is in the export of Tweakwise but the first one is shown as exponential (1.0E+14) which is done automatically by PHP itself.
Tweakwise doesn't accept exponential values resulting in imports not being run anymore.

Environment
--
* PHP Version: 7.2
* Magento Version: 2.3.4
* Tweakwise Version: 2.0.1
* Tweakwise Export Version: 1.3.8
* Magento Deploy Mode: production

Steps to reproduce
--
1. Install Magento v2.3.4 from `develop` branch.
2. Configure product with (for example) a price like 99999999999999.99900 (14 nines before the decimal)
3. Export to Tweakwise

Actual result
--
1. See results of price in the tweakwise export (formatted like `1.0E+14`)

Expected result
--
Either one of the following results
- [ ] Price is formatted like `99999999999999.99` or even rounded, thus `100000000000000.00`
- [ ] The exponential value `1.0E+14` is accepted by Tweakwise (outside of scope of this module)

Earlier contact with Tweakwise (partly, translated from dutch)
--
In one of our project we stumbled upon an issue resulting in Tweakwise not being able to complete imports. This issue has been reported at Tweakwise and is known as ticket no. 4633 (currently closed).

Tweakwise pointed out that the export had a faulty value (see aforementioned ticket no.) on which the import crashes. We investigated this issue and found out that the new Magento version allows higher values for decimals resulting in exponential values for prices.

All float (decimal) values higher than 9999999999999.99900 (13 nines before the decimal pointer) are being returned as an exponential value by PHP (so 1.0E+14 for example).
To prevent such values one can use `sprintf('%0.5f', $val)` for example to return a string of the correct represented value on which this could be passed to the XML correctly.

An update has been applied where the decimal table can hold higher values since either Magento version 2.3.3 or 2.3.4 (most probably the latter). We're unable to use the current (high) values with the current setup of Tweakwise as they can not seem to read exponential values (https://3v4l.org/IhDid). We also reproduced this issue on our test enviroment.

**Comment by edwinljacobs** [comment]
Thanks for reporting, we will incorporate your suggestion.

**Comment by edwinljacobs** [comment]
Hi,

We added branch https://github.com/EmicoEcommerce/Magento2TweakwiseExport/tree/issue/122812-format-exponentials to fix this issue. The change boils down to https://github.com/EmicoEcommerce/Magento2TweakwiseExport/commit/38844645e09569ffc2ea01ec1ea63f5efdf1cb7f

Is it an option for you to check if it is working in your project by including emico/tweakwise-export "dev-issue/122812-format-exponentials" (perhaps you need to add 'as 1.5.0')

I couldn't help but notice that you are a few versions behind the latest releases of both this module and the export module, is there a specific reason for that? In other words, do you see upgrade issues?

With kind regards

**Comment by edwinljacobs** [comment]
Hi,

We just released https://github.com/EmicoEcommerce/Magento2TweakwiseExport/releases/tag/v1.5.5 where this issue should be fixed. 

With kind regards

**Comment by kozie** [comment]
Sorry for not responding earlier. I will soon update the module and check if this issue has been resolved on our side. I will update this issue accordingly.

Thanks for the quick actions for now! :)

>  couldn't help but notice that you are a few versions behind the latest releases of both this module and the export module, is there a specific reason for that? In other words, do you see upgrade issues?

No specific reasons nor did we experience any issues while upgrading.

**Comment by edwinljacobs** [comment]
No problem, hopefully the update will fix your issue. Feel free to reopen this issue if you experience any problems.

With kind regards
