### ISSUE TITLE
Search autosuggest throws error when product is missing images 

### ISSUE THREAD

**Issue by rlaven** [EmicoEcommerce/Magento2Tweakwise-archived#113]
Issue Brief
--
While developing on a local machine without images i came across an error in the autosuggest of the minicart. Locally I dont have any images and rely on the placeholders Magento shows when a product is missing images. While searching I didn't see any products being added to the search-autocomplete, upon investigating the ajax response I saw the following error:

``<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getData() on null in /var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php:500
Stack trace:
#0 /var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php(470): Magento\Catalog\Helper\Image-&gt;initBaseFile()
#1 /var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php(551): Magento\Catalog\Helper\Image-&gt;applyScheduledActions()
#2 /var/www/woonexpress.nl/vendor/magento/module-catalog/Block/Product/ImageBuilder.php(133): Magento\Catalog\Helper\Image-&gt;getResizedImageInfo()
#3 /var/www/woonexpress.nl/generated/code/Magento/Catalog/Block/Product/ImageBuilder/Proxy.php(119): Magento\Catalog\Block\Product\ImageBuilder-&gt;create()
#4 /var/www/woonexpress.nl/vendor/emico/tweakwise/src/Model/Autocomplete/DataProvider/ProductItem.php(117): Magento\Catalog\Block\Product\ImageBuilder\Proxy-&gt;create(Object(Magento\Catalog\Model\Product\Interceptor), 'product_thumbna...', Array)
#5 /var/www/woonexpress.nl/vendor/emico/tweakwise/src/Model/Autocompl in <b>/var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php</b> on line <b>500</b><br />
``
When checking the file ProductItem.php it seems to be going wrong on line 84. 
`$image = $this->getImage();`

The getImage has a return type of Image, but in my case returns null, because no images exist. 

Environment
--
* PHP Version: 7.1
* Magento Version: 2.2.11
* Tweakwise Version: 2.1.8
* Tweakwise Export Version: 1.5.4
* Magento Deploy Mode: development

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Create a product without any images, and rely on magento to provide the placeholder image.
3. Search for the  product in the mini.search
4. Check the network tab of the browser to see the response.

Actual result
--
1. The response shows an error
``<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getData() on null in /var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php:500
Stack trace:
#0 /var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php(470): Magento\Catalog\Helper\Image-&gt;initBaseFile()
#1 /var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php(551): Magento\Catalog\Helper\Image-&gt;applyScheduledActions()
#2 /var/www/woonexpress.nl/vendor/magento/module-catalog/Block/Product/ImageBuilder.php(133): Magento\Catalog\Helper\Image-&gt;getResizedImageInfo()
#3 /var/www/woonexpress.nl/generated/code/Magento/Catalog/Block/Product/ImageBuilder/Proxy.php(119): Magento\Catalog\Block\Product\ImageBuilder-&gt;create()
#4 /var/www/woonexpress.nl/vendor/emico/tweakwise/src/Model/Autocomplete/DataProvider/ProductItem.php(117): Magento\Catalog\Block\Product\ImageBuilder\Proxy-&gt;create(Object(Magento\Catalog\Model\Product\Interceptor), 'product_thumbna...', Array)
#5 /var/www/woonexpress.nl/vendor/emico/tweakwise/src/Model/Autocompl in <b>/var/www/woonexpress.nl/vendor/magento/module-catalog/Helper/Image.php</b> on line <b>500</b><br />
``
3. No products are shown in the autosuggest

Expected result
--
List the expected results as a bullet list of expectations
- Products are shown in the autosuggest
- Products without an image will get the Magento placeholder image

**Comment by edwinljacobs** [comment]
Thanks for reporting, ill look into it

**Comment by edwinljacobs** [comment]
Hi,

I think we have a fix for this issue. We created branch https://github.com/EmicoEcommerce/Magento2Tweakwise/tree/issue/113-autocomplete-error-missing-image with the potential fix.

The change is a oneliner (luckily) and can be found here https://github.com/EmicoEcommerce/Magento2Tweakwise/commit/4f3f0b2a6d718fb150e7d9f1c6690d2817479321 could you verify if this fixes your issue? If so we will merge and release it.

With kind regards

**Comment by rlaven** [comment]
I am now getting products so that seems to work again, thank you for the quick fix.

However, for some reason the placeholder images are not showing, please see below screenshot
![image](https://user-images.githubusercontent.com/5774383/77047691-74f66500-69c5-11ea-88a7-3ee8f0c43ec5.png)

The actual image name seems to be missing. So instead of `placeholder/.jpg` it should be `placeholder/small_image.jpg`

**Comment by edwinljacobs** [comment]
Yeah I noticed this as well. I thought it had to do with my configuration. Apparently not :(
I think I need to set the "imageId" on the ImageBuilder in magento/module-catalog/Block/Product/ImageBuilder.php, i'll try that.

**Comment by edwinljacobs** [comment]
That seems to work. Could you take another look?

WIth kind regards

**Comment by rlaven** [comment]
Hi @edwinljacobs, 

For some reason it doesn't seem to work for me. When inspecting the request i get the following error:

`<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Block\Product\ImageFactory\Proxy::create() must be of the type array, object given, called in /var/www/woonexpress.nl/vendor/emico/tweakwise/src/Model/Autocomplete/DataProvider/ProductItem.php on line 124 and defined in /var/www/woonexpress.nl/generated/code/Magento/Catalog/Block/Product/ImageFactory/Proxy.php:93
Stack trace:
#0 /var/www/woonexpress.nl/vendor/emico/tweakwise/src/Model/Autocomplete/DataProvider/ProductItem.php(124): Magento\Catalog\Block\Product\ImageFactory\Proxy-&gt;create(Object(Magento\Catalog\Model\Product\Interceptor), 'product_thumbna...', Array)
#1 /var/www/woonexpress.nl/vendor/emico/tweakwise/src/Model/Autocomplete/DataProvider/ProductItem.php(79): Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem-&gt;getImage()
#2 /var/www/woonexpress.nl/vendor/magento/module-search/Controller/Ajax/Suggest.php(47): Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem-&gt;toArray()
#3 /var/www/woonexpress.nl/generated/code/Magento/Searc in <b>/var/www/woonexpress.nl/generated/code/Magento/Catalog/Block/Product/ImageFactory/Proxy.php</b> on line <b>93</b><br />
`

**Comment by rlaven** [comment]
@edwinljacobs Yes this looks right! Thanks for the quick responses. When can I expect a new version of the module to include in my project?

**Comment by edwinljacobs** [comment]
Release schedule is currently on wednesday. So ill release this next wednesday.

With kind regards

**Comment by rlaven** [comment]
Hi @edwinljacobs 

Could you maybe tell me if the release is still planned for today?

**Comment by edwinljacobs** [comment]
Yes it is, I was just about to make the release.

**Comment by edwinljacobs** [comment]
Hi,

We just release https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v2.1.9 where this issue is fixed!

With kind regards
