### ISSUE TITLE
Filter options with umlaut symbols aren't displayed on Frontend

### ISSUE THREAD

**Issue by yuriichayka** [EmicoEcommerce/Magento2Tweakwise-archived#116]
Filter options with umlaut symbols aren't displayed on Frontend, category page
--
We have found the issue with "umlaut/special characters" symbols in Tweakwise module during implementation for our customer.
In case, the attribute value contains the "umlaut" symbols, the following value is not displayed in filter section.
Value examples: "Grün", "Weiß","Türkis".

As we detected, the issue appears in Emico\Tweakwise\Model\Catalog\Layer\Filter, getOptionIdByLabel(label) and getItemByOptionId($optionId) methods. Filters with umlauts have html symbols here in names, and couldn't be matched.
Environment
--
* PHP Version: 7.1.32
* Magento Version: Magento Enterprise 2.3.2
* Tweakwise Version: 2.0.0
* Tweakwise Export Version: 1.3.3
* Magento Deploy Mode: (production|development)
* Third party modules:

Steps to reproduce
--
1. Install Magento
2. Adjust some filters to have umlauts in values/labels
3. [Example] Configure color filter in Tweakwise/Magento as on the White.png snapshot
![White](https://user-images.githubusercontent.com/34608132/77737919-91bf1800-7017-11ea-96c3-e96f2961103a.png)
4. Check such filters displaying on Magento POP, 
 Emico\Tweakwise\Model\Catalog\Layer\Filter in particular

Actual result
--
Umlauts symbols are encoded when matching filter, so can't be matched and aren't displayed on FE. 
![Umlauts](https://user-images.githubusercontent.com/34608132/77737927-9683cc00-7017-11ea-92e5-18d19982847e.png)
Expected result
--
Umlauts symbols are properly handled when matching filters

**Comment by edwinljacobs** [comment]
Thanks for reporting, we will look into it

**Comment by edwinljacobs** [comment]
Hi I believe I have a fix for this issue. In https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/a47e6d3a9df6ade5abbc489fcd666d1b8cdbed00/src/Model/Catalog/Layer/Filter/Item.php#L77

There used to be a call to htmlentities which caused the issue. This has been removed in branch: issue/116-umlaut-special-char, see commit https://github.com/EmicoEcommerce/Magento2Tweakwise/commit/a47e6d3a9df6ade5abbc489fcd666d1b8cdbed00. You can test this branch by "composer require emico/tweakwise dev-issue/116-umlaut-special-char".

Can you check if this fixes your issue?

With kind regards

**Comment by yuriichayka** [comment]
Hello. Thanks for the response. 
We've already fixed such problem on our project by encoding/decoding HTML entities in Client class. 
The purpose of this issue is to make sure that such problem won't be present in future.
I won't be checking this fix, sorry. Don't have enough time. 

But it is good to hear that it is already fixed. 
You can close this ticket.

**Comment by edwinljacobs** [comment]
Ah ok, good to know. Nice to hear its already fixed in your project. Ill include the fix in the next release. The time issue sounds familiar, good luck!

With kind regards
