### ISSUE TITLE
Tweakwise configuration only allows 2 recommendations on PDP

### ISSUE THREAD

**Issue by jkekkel** [EmicoEcommerce/Magento2Tweakwise-archived#119]
Issue Brief
--
On our Magento 1 store we use the API of Tweakwise. In our new Magento 2 shop we use the Tweakwise extension. In Magento 1 we have 4 different recommendations:
* Cross sell 1: "Matching products"
* Cross sell 2: "Matching pillows" (often 10+, so I don't want to show these in crosssell 1 as well. Otherwise it won't be user friendly)
* Upsell 1: "Color variant"
* Upsell 2: "Product variant" (often the same product, but then with 1 extra chair e.g.)
But I'd also like one extra "cross sell" block for "Related products"/"Cash bargains". If you buy for example a loungeset I'd really like to show our sunshades as well.

But unfortunately I can only use 1 cross sell field and 1 up sell field in the Magento 2 Tweakwise extension.
![image](https://user-images.githubusercontent.com/60736470/80595928-cf9fc980-8a25-11ea-8fba-20aea46a44d3.png)
This forces me to combina all cross- and upsell options we have which has a bad experience for our users.

Expected result
- [ ] Next to the current default crosssell and upsell template you also give the possibility for at least 2 extra recommendations.
![image](https://user-images.githubusercontent.com/60736470/80596730-1e019800-8a27-11ea-8ea1-58275a57e85c.png)

**Comment by stijnbernards** [comment]
Hi @jkekkel ,

It's been almost a year but I'm cleaning up a few old open issues.
Your request seems like quite a case specific request. I think the implementation should be done in your shop via a custom module and not in the open source Tweakwise Module.

I'm closing this Issue.

Cheers.

**Comment by jkekkel** [comment]
I disagree. You make the assumption you only have one cross sell and one
upsell. Maybe nobody complains about it bit almost Evert company had more
than two rules.

For example:
- color alternatives
- products from the same brand
- products in the same series
- products from b choice
- look a likes
- different sizes
- etc etc

Now everybody who users this module is Just stuffing everything in one
recommendation bit that's far from Ideal.

So i'd suggest to set this on the roadmap.
At this moment I'm already using a different tool to fullfill my needs but
it loads client side, that's also not Ideal.

Looking forward hearing from you.

With kind regards,
Jan Karel Ekkel

Op wo 21 apr. 2021 19:06 schreef Stijn Bernards ***@***.***>:

**Comment by jkekkel** [comment]
Hi Jan Karel,

Gezien het om een feature request gaat, is het voor nu prima dat het issue in Github gesloten is, aangezien dat voornamelijk voor bugs bedoeld is. Ik heb daarom je wens bij onze Product Owner neergelegd.

Met vriendelijke groet,

Mathilde Visscher

038 850 1001
Punterweg 2, 8042 PB, Zwolle

www.tweakwise.com<http://www.tweakwise.com/>
support.tweakwise.com<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8cFnFhW16Bb-959hl3kW7_k2841CXdp3VPwQ_Q2P2FGlW2bzNJB60pkht101?te=W3R5hFj26QkHhW4hKKYc49RFxnW4mBcpt4mCWVcf1JxwY5V3&si=8000000003944044&pi=ebc21d73-6194-45f8-b0c1-3ef1346b2cc4>
www.tweakwisestatus.com<http://www.tweakwisestatus.com/>
[cid:007dfba8c030a1a424b7558e1840b759]

woensdag 21 april 2021 21:46:07 +0200, Jan Karel Ekkel ***@***.******@***.***>>:
I disagree. You make the assumption you only have one cross sell and one upsell. Maybe nobody complains about it bit almost Evert company had more than two rules.

For example:
- color alternatives
- products from the same brand
- products in the same series
- products from b choice
- look a likes
- different sizes
- etc etc

Now everybody who users this module is Just stuffing everything in one recommendation bit that's far from Ideal.

So i'd suggest to set this on the roadmap.
At this moment I'm already using a different tool to fullfill my needs but it loads client side, that's also not Ideal.

Looking forward hearing from you.

With kind regards,
Jan Karel Ekkel

Op wo 21 apr. 2021 19:06 schreef Stijn Bernards < ***@***.******@***.***>>:

Hi @jkekkel<https://t.sidekickopen90.com/s3t/c/5/f18dQhb0S7kF8cFnFhW16Bb-959hl3kW7_k2841CXdp3VPwQ_Q2P2FGlW2bzNJB60pkht101?te=W3R5hFj4cm2zwW3P28X24hCPvhW43T4N-3XWHdG39wV2&si=8000000003944044&pi=ebc21d73-6194-45f8-b0c1-3ef1346b2cc4> ,

It's been almost a year but I'm cleaning up a few old open issues.
Your request seems like quite a case specific request. I think the implementation should be done in your shop via a custom module and not in the open source Tweakwise Module.

I'm closing this Issue.

Cheers.
