### ISSUE TITLE
Price filter is not working

### ISSUE THREAD

**Issue by mediactbv** [EmicoEcommerce/Magento2Tweakwise-archived#12]
When going to the search page with a search result, it shows the search result with filters and the left side. On top are the category filters. When clicking on a category filter you are directly going to that category without the search result.

Environment
- PHP Version: 70
- Magento Version: 2.1.7
- Tweakwise Version: 1.0.1
- Tweakwise Export Version: 1.0.2
- Magento Deploy Mode: production

Steps to reproduce

1 go to a search result page with a search term or to a category with layered navigation, make sure there are price filters available on those pages. After changing the price filter the search result/category  is not updated and filtered based on the price.

Actual result
--
1.  After changing the price filter the search result/category  is not updated and filtered based on the price.

Expected result
--
1. After changing the price filter the search result should be filtered for those prices

**Comment by Fgruntjes** [comment]
This was fixed with 118001ddb85fa90ec50648ad491272f251554426
