### ISSUE TITLE
Can't uncheck any filters on product listing pages

### ISSUE THREAD

**Issue by gerhard50five** [EmicoEcommerce/Magento2Tweakwise-archived#125]
Issue Brief
--
When a filter has been selected, clicking on it again does not remove the filter from the page. 

Environment
--
* PHP Version: (5.6|7.0|7.1)
* Magento Version: 2.3.5-p2
* Tweakwise Version: 2.2.0
* Tweakwise Export Version: 1.6.3
* Magento Deploy Mode: All

Steps to reproduce
--
1. Click on a filter on a product listing page
2. When the page has refreshed, click on the same (selected) filter again

Actual result
--
1. The page reloads

Expected result
--
- The page should reload with the filter removed

Additional information
--
- This feature broke when we upgraded from v2.1.0 to v2.2.0
- There are no javascript errors visible
- I updated the Tweakwise module to version 2.3.2 but the issue persists

**Comment by edwinljacobs** [comment]
Hi,

Bases on what I saw, the filter url of the selected checkbox still contains that value. It should not. So indeed it is not a Javascript error or anything like that. 
Method: ```getAttributeRemoveUrl``` in class ```src/Model/Catalog/Layer/Url/Strategy/QueryParameterStrategy.php```  is responsible for constructing that url. I assume that you use query parameter filter url strategy based on the url (You can check this in Stores > Configuration > Catalog > Tweakwise > Layered navigation > URL strategy, there are two options, query and path.

Are there any custom changes? 

Ill check tomorrow on a fresh install.

With kind regards

**Comment by gerhard50five** [comment]
Hi Edwin,

Thanks for the reply.

Regarding **custom changes**. It looks like we're using a plugin.

`di.xml`
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem">
        <plugin name="emico-tweakwise-add-is-bundle" type="Fiftyfive\Tweakwise\Plugin\Model\Autocomplete\DataProvider\ProductItemPlugin"/>
    </type>
</config>`

`<?php
/**
 * Fiftyfive Tweakwise added is bundle to item provider.
 *
 * @category  Fiftyfive
 * @package   Fiftyfive\Tweakwise
 * @author    Serhii Checkanov <seche@smile.fr>
 * @copyright 2020 Smile
 */

namespace Fiftyfive\Tweakwise\Plugin\Model\Autocomplete\DataProvider;

use Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem;

/**
 * Class ProductItemPlugin
 *
 * @package Fiftyfive\Tweakwise\Plugin\Model\Autocomplete\DataProvider\ProductItemPlugin
 */
class ProductItemPlugin extends ProductItem
{
    /**
     * Added to result is_bundle option.
     *
     * @param ProductItem $provider
     * @param array $result
     * @return array
     */
    public function afterToArray(ProductItem $provider, array $result) : array
    {
        $result['is_bundle'] = $provider->product->getTypeId() == 'bundle';
        $result['is_available'] = $provider->product->isAvailable();

        return $result;
    }
}`

Apart from these custom changes we have edited the phtml templates a little bit. I have deleted them all to test if the problem exists in there but it still persisted. 

This is what our Layered navigation configuration looks like at the moment. This didn't change since the last update. 

![image](https://user-images.githubusercontent.com/44646660/93294620-54c82700-f7eb-11ea-89a8-2b81bdf7b041.png)

**Comment by edwinljacobs** [comment]
Thanks, ill look into it. I dont think that the autocomplete plugin should have any impact on the matter.

I hope to have an update today. 

With kind regards

**Comment by edwinljacobs** [comment]
Apparently made an error in an if check :( 

This should be fixed with release: https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v2.3.3

With kind regards

**Comment by gerhard50five** [comment]
Thank you Edwin! I will test this out on my side as well and report back.

**Comment by gerhard50five** [comment]
It works great, Thank you very much for the speedy replies and fix.

**Comment by edwinljacobs** [comment]
No Problem :)

Case closed!

With kind regards
