### ISSUE TITLE
Error in when going to search results page

### ISSUE THREAD

**Issue by rlaven** [EmicoEcommerce/Magento2Tweakwise-archived#132]
Issue Brief
--
I've installed Tweakwise on a Magento webshop, exported the feed and loaded it into navigator. I get filters and search itself works fine. Except when I visit the search results page I get an error. See the steps below to reproduce.

Could this be configuration on the Tweakwise side or is it an issue in Magento and the module?

Environment
--
* PHP Version: (7.1.33)
* Magento Version: 2.3.5-p2
* Tweakwise Version: 3.1.0
* Tweakwise Export Version: 2.0.1
* Magento Deploy Mode: development
* Third party modules:

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Search for a term and press enter to go to search results page
4. See error.

Actual result
--
`Fatal error: Declaration of Emico\Tweakwise\Model\Client\Request\SearchRequestTrait::getParameter(string $parameter) must be compatible with Emico\Tweakwise\Model\Client\Request::getParameter($parameter) in /var/www/xxx/vendor/emico/tweakwise/src/Model/Client/Request/ProductSearchRequest.php on line 20`

Expected result
--
List of matched products and sidebar

**Comment by edwinljacobs** [comment]
Hi,

I didn't have this while testing, so I missed that :( that is sloppy.... The fix is in release v3.1.1

**Comment by rlaven** [comment]
I tested again with version 3.1.1 and the issue seems to be resolved. 

Thanks for the quick answer!
