### ISSUE TITLE
upgrade to 1.0.4 from composer results in server error

### ISSUE THREAD

**Issue by martijnrmediact** [EmicoEcommerce/Magento2Tweakwise-archived#14]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 7.0
* Magento Version: ME 2.1.9
* Tweakwise Version: 1.0.3/1.0.4
* Tweakwise Export Version: 1.0.6
* Magento Deploy Mode: production

Steps to reproduce
--
1. upgrade to 1.0.4 from 1.0.3 with composer and --no-dev
2. run setup:upgrade and di:compile and compile theme, flush cache
3. go to a category page, the page will give a server error

We have  fix:

after above run composer require emico/tweakwise:1.0.3 then run require emico/tweakwise:1.0.4 and flush cache and it works. The only difference is that dev modules are being installed.

Actual result
--
1. the category and product page have a server error
Expected result
--
the category and product page should show correct

**Comment by Fgruntjes** [comment]
Could you test again with the latest version, although we could never reproduce the issue is expected to be fixed.

**Comment by Fgruntjes** [comment]
Any news?

**Comment by martijnrmediact** [comment]
Thanx for the update, we didnt plan a release this sprint to production, this sprint. I will do a quick check today.

**Comment by Fgruntjes** [comment]
Can I assume the issue was solved?

**Comment by martijnrmediact** [comment]
@Fgruntjes we tested the lastest version and this issue has been resolved.
