### ISSUE TITLE
Feature request: use Magento escaping in phtml templates

### ISSUE THREAD

**Issue by arnoudhgz** [EmicoEcommerce/Magento2Tweakwise-archived#143]
When I look into the phtml templates stuff seems not escaped or escaped with htmlentities. Is it not possible to use the native Magento `Magento\Framework\Escaper $escaper` class that is available in every template?

Also when an variable is outputted and should not be escaped there should be a comment `/** @noEscape */` in front of it.

**Comment by Hnto** [comment]
@arnoudhgz We've added this to our backlog so I'm closing this issue
