### ISSUE TITLE
Can't close filter popup after ajax filtering on mobile

### ISSUE THREAD

**Issue by vasiok32k** [EmicoEcommerce/Magento2Tweakwise-archived#144]
Hi all,
There is bug on POP on mobile when using ajax filtering. I can't close filter popup after ajax filtering on POP on mobile. 

I investigated issue and found that response rendering whole filter sidebar including Filter Title that contain cross icon on mobile and is actually toggle for close the popup when you will click on cross icon. 

**I have a solution for that so I could create PR to fix that or you could create you own fix for that.**

Version of "emico/tweakwise" module is "v3.2.1".

Please let me know about approving of that bug and acceptable way to fix it.

Thanks for future help.

**Comment by stijnbernards** [comment]
Hi Vasyl,

Sure you can go ahead and create a merge request for this issue.
Do you need any further assistance with this?

**Comment by vasiok32k** [comment]
Hi stijnbernards
Created PR
https://github.com/EmicoEcommerce/Magento2Tweakwise/pull/145

**Comment by stijnbernards** [comment]
Hi,

Thank you for your contribution! 
I'll check and test this MR in a bit!
