### ISSUE TITLE
Ajax filtering not working with pagination

### ISSUE THREAD

**Issue by Alainvdz99** [EmicoEcommerce/Magento2Tweakwise-archived#165]
Issue Brief
--
When being on the next page of a plp, filtering wont work anymore if there is only 1 page of products left after the filter. Problem is that url parameter "p=2" (2 stands for the pagination) will stay in the url when there is only 1 page left. 

Environment
--
* PHP Version: (7.4)
* Magento Version: 2.4.2-p1
* Tweakwise Version: v3.3.1
* Tweakwise Export Version: v.2.1.0
* Magento Deploy Mode: production|development
* Third party modules: -

Steps to reproduce
--
1. Enable Ajax filtering
2. Go to a PLP with more than 24 products
3. Go to the next page (page 2)
4. Use a filter which will result with not having more than 24 products

Actual result
--
1. Filtering will not work
2. Request url to tweakwise will return 0 items because its using page 2 (`tn_p1=2` in url), when using `tn_p1=1` in the url, it does give the correct items back
![Screen Shot 2021-06-18 at 14 14 16](https://user-images.githubusercontent.com/37347746/122560141-8606a980-d040-11eb-8417-80962524ff04.png)

Expected result
--
List the expected results as a bullet list of expectations
- [ ] When there is no next page with that filter, return the first page

**Comment by simonjanguapa** [comment]
We are experiencing this issue as well.

**Comment by CyberSecutor** [comment]
We are also experiencing this with Magento 2.3.4-p1 and module version 3.3.4

**Comment by Hnto** [comment]
@Alainvdz99 Issue has been fixed in v4.0.4.
