### ISSUE TITLE
Errors during complication

### ISSUE THREAD

**Issue by LarsRezelman** [EmicoEcommerce/Magento2Tweakwise-archived#17]
Tweakwise extension 1.0.6
Magento 2.1.9
PHP 7

When running the command bin/magento setup:di:compile, our developper gets the following Error:
https://files.slack.com/files-pri/T5VS0A9BK-F7R358485/screen_shot_2017-10-27_at_13.21.51.png

**Comment by EduardSelles** [comment]
Hi lars,

Can you upload the screenshot? We do not have permission to open your Slack account :-)

Thanks!

**Comment by LarsRezelman** [comment]
![screen_shot_2017-10-27_at_13 21 51](https://user-images.githubusercontent.com/32707547/32171956-2d046cb4-bd7a-11e7-8343-0b318fbbd6ee.png)
