### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by DerFrenk** [EmicoEcommerce/Magento2Tweakwise-archived#177]
Issue Brief
--
We have several shops that use emico/tweakwise. In all those sites ajax filtering is disabled. When I add a price filter on a category page, everything works fine. I get a URL like `collection/categorie/price/123-456/`. Go to the pagination, click on page two, and you'll get url `collection/categorie/price/123-456/?p=2` as expected. However, you'll see exactly the same products as on the previous page.

When I downgrade emico/tweakwise to version 3.3.2, everything works fine. From 3.3.3 on it is broken. I traced the issue down to this commit: https://github.com/EmicoEcommerce/Magento2Tweakwise/commit/d3b472540c9fd6e2636ffc5710f334abf067b272. I don't exactly know why, but `$request->has('filter_path')` is true, so `$navigationRequest->setPage($page);` won't be executed and the results of p1 will be shown.

All those sites have a 'basic' tweakwise integration without any custom overrides a.f.a.i.k and I can see.

Environment
--
* PHP Version: Multiple 7.x versions
* Magento Version: ~2.3.5
* Tweakwise Version: >=3.3.3
* Magento Deploy Mode: production
* Third party modules: some amasty and some custom modules

Steps to reproduce
--
1. Install Magento and Tweakwise
2. Add a price filter or some other filter
3. Go to page 2

Actual result
--
1. On page 2, you see the same results as on page 1

Expected result
--
- [ ] On page 2 I see different products than on page 1

**Comment by gjportegies** [comment]
We're also experiencing this issue on Tweakwise version 3.3.8

- PHP Version: 7.4.23
- Magento Version: 2.4.3
- Tweakwise Version: 3.3.8
- Tweakwise Export Version: 3.2.1

**Comment by Hnto** [comment]
This issue has been fixed and released under version v4.0.1
