### ISSUE TITLE
Old values not deleted from tweakwise_attribute_slug table.

### ISSUE THREAD

**Issue by gjportegies** [EmicoEcommerce/Magento2Tweakwise-archived#200]
Issue Brief
--
We recently ran into an issue where we didn't get any results when filtering on a specific size (`eg. /categorieen/schoenen.html/maat/37-5/`) although we did have products available for this filter value. 
When looking further into this issue I found out that there were old attribute values in the `tweakwise_attribute_slug` which were not used anymore.

We had an text swatch attribute `maat` with the value 37.5. We've changed that value later on to 37,5. The old value was still available in the `tweakwise_attribute_slug` which didn't have any results anymore.

![old-entries-tweakwise-attribute-slug](https://user-images.githubusercontent.com/6707410/141150289-9b69516b-0237-449c-9b43-97852c724fe1.png)

To fix this issue I've truncated the table so the values will be regenerated. Although this issue will appear again when changing the attribute values.

Preconditions
--
- Using SEO Path Slugs as URL strategy.

Environment
--
* PHP Version: 7.4
* Magento Version: 2.4.3
* Tweakwise Version: 4.0.1
* Tweakwise Export Version: 4.0.1
* Magento Deploy Mode: production

**Comment by Hnto** [comment]
@gjportegies I've also reproduced the issue and we will be working on a fix in the next release.
