### ISSUE TITLE
Not possible to get the active filters

### ISSUE THREAD

**Issue by JKingma** [EmicoEcommerce/Magento2Tweakwise-archived#22]
Issue Brief
--
What is the purpose of this issue? Explain the background context.
For one of the webshops we build, we would like to show a button or link to remove all active filters. This is not possible since the function to get the active filters always returns an empty array.

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.9
* Tweakwise Version: 1.0.7
* Magento Deploy Mode: production && development

Steps to reproduce
--
1. Select a configured filter in the frontend and wait for the page to reload.
2. Look for a button or link to remove all active filters.

Actual result
--
1. No active filters are shown
2. The function `$block->getLayer()->getState()->getFilters()` in vendor/emico/tweakwise/src/view/frontend/templates/product/navigation/view.phtml always returns an empty array.
3. data-count therefor is always 0.

Expected result
--
1. The function `$block->getLayer()->getState()->getFilters()` in vendor/emico/tweakwise/src/view/frontend/templates/product/navigation/view.phtml always returns a filled array of active filters.
2. data-count shows the number of active filters.
3. All filters can be removed at once using a "remove all filter" button.

**Comment by JKingma** [comment]
@Fgruntjes Any update on this? Is there anything I can clarify?

**Comment by Fgruntjes** [comment]
@JKingma 

No the information provided is very clear, thank you. This issue is on our roadmap but we did not have the time to fix it yet. For any planning related questions please contact Tweakwise.

**Comment by edwinknol-mediact** [comment]
@Fgruntjes 
Do you have an update about this issue?

Kind regards,

Edwin
