### ISSUE TITLE
When updating to 4.1.1 i get the following error

### ISSUE THREAD

**Issue by leonhelmus** [EmicoEcommerce/Magento2Tweakwise-archived#228]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: (5.6|7.0|7.1)
* 7.7
* Magento Version:
* 2.4.3-p1
* Tweakwise Version:
* 4.1.1

Steps to reproduce
--

1. After updating to 4.1.1 and i do a bin/magento setup:upgrade i get an following error

Actual result
--
Unable to apply data patch Emico\Tweakwise\Setup\Patch\Data\AddFilterAndFilterValuesCategoryAttribute for module Emico_Tweakwise. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3749' for key 'catalog_eav_attribute.PRIMARY', query was: INSERT INTO `catalog_eav_attribute` (`attribute_id`, `is_global`, `is_visible`, `is_used_in_grid`, `is_visible_in_grid`, `is_filterable_in_grid`, `frontend_input_renderer`, `is_searchable`, `is_filterable`, `is_comparable`, `is_visible_on_front`, `is_wysiwyg_enabled`, `is_html_allowed_on_front`, `is_visible_in_advanced_search`, `is_filterable_in_search`, `used_in_product_listing`, `used_for_sort_by`, `apply_to`, `position`, `is_used_for_promo_rules`, `search_weight`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

Expected result
--
No error is shown

**Comment by Hnto** [comment]
hi @leonhelmus I'm not able to reproduce the problem. Are you still experiencing this issue?

**Comment by leonhelmus** [comment]
No, for now this can be closed.
