### ISSUE TITLE
Bundled products and MSI

### ISSUE THREAD

**Issue by maxserv-woostelbos** [EmicoEcommerce/Magento2Tweakwise-archived#229]
Issue Brief
--
We installed the MSI meta package and started using this for our simple and bundled products. All of the products, including the bundled products, that are saleble should be exported to the navigator but unfortunately they are not. 

I've seen code in the TWK export extention with logic for MSI but we can't get any bundled products to be added to the navigator. What are we missing?

Environment
--
* PHP Version: (7.4)
* Magento Version: 2.4.3
* Tweakwise Version: 4.0.3
* Tweakwise Export Version: 4.1.2
* Magento Deploy Mode: (production)

Steps to reproduce
--
1. Confirm that bundled products are saleable: https://staging.magento.forza-intenso.keessmit.nl/intenso-bordanorough-s-220cm-dining-tuinset-7-delig-119393.html
2. Look in the [assigned category ](https://staging.magento.forza-intenso.keessmit.nl/tuinsets/) or [search results
](https://staging.magento.forza-intenso.keessmit.nl/catalogsearch/result/?q=119393) and check the product cannot be found

**Comment by Hnto** [comment]
@maxserv-woostelbos This issue has been fixed and will soon be released under version V4.1.3

**Comment by maxserv-woostelbos** [comment]
@Hnto The export module 4.0.4 has the fix right?  We already are using that version. Thanks for the fix and response 👍

**Comment by Hnto** [comment]
@maxserv-woostelbos Yes, exactly! I confused this module with the export :)
