### ISSUE TITLE
Upsell and Crossell blocks not displayed after product save

### ISSUE THREAD

**Issue by VesnaS** [EmicoEcommerce/Magento2Tweakwise-archived#23]
Hello,

We have one issue with the latest version of the extension.
As I understood, upsell and crosssell templates can be configured in 3 places:
- general configuration: M2 -> Admin -> Stores -> Configuration -> CATALOG -> Tweakwise -> Recommendations
- product configuration: M2 -> Admin -> Products -> Catalog -> Tweakwise
- category configuration: M2 -> Admin -> Products -> Categories -> Tweakwise

When displaying upsell and crosssell on product view page, if Tweakwise templates aren't configured on the product level, extension tries to load them from the category that the product belongs to.
If category doesn't have associated templates, then the ones configured in the general configuration are used.
In this case, upsell and crosssell blocks are displayed correctly.
But, if someone than saves product in admin, without changing anything related to Tweakwise templates, upsell and crosssell products are not displayed on frontend anymore.

**Steps to reproduce**

- Configure upsell and crosssell templates in general configuration, without setting templates on product or category level
- Upsell and crosssell blocks are displayed on frontend product view page
- If you than save product in admin, without changing anything related to Tweakwise, "tweakwise_upsell_template" and "tweakwise_crosssell_template" get value "-1" saved in database (this shouldn't happen), as this is the first value in dropdown list. This indicates to the extension that it shouldn't use "template id", but "template code" which in this case should have value set. As that is not the case, it ties to load non-existing template, and crosssell and upsell products aren't displayed on frontend.

**Environment**

Magneto 2.1.6
Latest version of the extension
PHP 7

**Comment by Fgruntjes** [comment]
Thank you for the issue report, we have managed to found and fix the bug.
