### ISSUE TITLE
Isssue Tweakwise/Ajax Navigation filtering

### ISSUE THREAD

**Issue by charlottegeven** [EmicoEcommerce/Magento2Tweakwise-archived#230]
This issue occurs on paginated pages. As an example I use https://www.brabantia.com/nl/afval-verzamelen/afvalemmers-prullenbakken/. 
When you scroll down on this page and put the cursor on the '2', you will see that this page links to:
https://www.brabantia.com/nl/tweakwise/ajax/navigation/?p=2 

If you click through, however, the page will go to: https://www.brabantia.com/nl/afval-verzamelen/afvalemmers-prullenbakken/?p=2, which is correct. 
 
The Ajax Navigation makes sure that certain parts of the page (like the products in this case), can be refreshed without reloading the whole page. JavaScript is used for this. The URL with 'tweakwise/ajax/navigation/' in it is only visible when JavaScript rendering is enabled.
 
So what's the problem?  
The Google bot always passes by in two stages. We call these phases the first wave of crawling and the second wave of crawling. 
- In the first wave of crawling, Google does not crawl JavaScript. Then everything goes well. 
- In the second wave of crawling, Google does crawl JavaScript and thus ends up at the URL with "tweakwise/ajax/navigation/". 
 
As a result, Google sees two different situations in pagination. This leads to possible issues with the crawling of the website and with the link value being forwarded. 
 
Solution
The links to paginated pages must have the correct URL (for example: https://www.brabantia.com/nl/afval-verzamelen/afvalemmers-prullenbakken/?p=2 ) both without and with JavaScript rendering.

Environment
--
* PHP Version: (7.4)
* Magento Version: 2.3.7/ p-2
* Tweakwise Version: 4.0.8.
* Tweakwise Export Version:
* Magento Deploy Mode: (production|development)
* Third party modules:

Steps to reproduce
This issue occurs on paginated pages. As an example I use https://www.brabantia.com/nl/afval-verzamelen/afvalemmers-prullenbakken/. 
When you scroll down on this page and put the cursor on the '2', you will see that this page links to:
 
If you click through, however, the page will go to: https://www.brabantia.com/nl/afval-verzamelen/afvalemmers-prullenbakken/?p=2, which is correct. 
 
The Ajax Navigation makes sure that certain parts of the page (like the products in this case), can be refreshed without reloading the whole page. JavaScript is used for this. The URL with 'tweakwise/ajax/navigation/' in it is only visible when JavaScript rendering is enabled.
 
So what's the problem?  
The Google bot always passes by in two stages. We call these phases the first wave of crawling and the second wave of crawling. 
- In the first wave of crawling, Google does not crawl JavaScript. Then everything goes well. 
- In the second wave of crawling, Google does crawl JavaScript and thus ends up at the URL with "tweakwise/ajax/navigation/". 
 
As a result, Google sees two different situations in pagination. This leads to possible issues with the crawling of the website and with the link value being forwarded. 
 
Solution
The links to paginated pages must have the correct URL (for example: https://www.brabantia.com/nl/afval-verzamelen/afvalemmers-prullenbakken/?p=2 ) both without and with JavaScript rendering.

**Comment by Hnto** [comment]
@charlottegeven Thanks for mentioning this. I have created an internal issue for this. I can't promise it will be picked up asap but I'll be sure to update you.

**Comment by charlottegeven** [comment]
@Hnto Oke thank you, hope to hear it.
