### ISSUE TITLE
Browse back button on POP doesn't work (navigation issue)

### ISSUE THREAD

**Issue by mischabraam** [EmicoEcommerce/Magento2Tweakwise-archived#239]
Issue Brief
--
The "back" button of my browser (Chrome on MacOS) doesn't reload the products on a POP. 

Case is when we're on a POP and navigate to the second page. The products are loaded using AJAX and the URL changes to `http://example.com/pop/?p=2`. This is correct. However, if we now click the back button of our browser, the URL changes back to what it was, but nothing else happens. The products are not reloaded again and the navigation buttons still show that the second page is active.

See a case at the following video:  https://watch.screencastify.com/v/ZKWfv88YVf9mObEc3XCF 

Environment
--
* PHP Version: 7.4
* Magento Version: 2.4.2-p1
* Tweakwise Version: 4.1.2
* Tweakwise Export Version: 4.0.3
* Magento Deploy Mode: production

Steps to reproduce
--
1. See video:  https://watch.screencastify.com/v/ZKWfv88YVf9mObEc3XCF

Actual result
--
1. Products are still the products from page 2.

Expected result
--
List the expected results as a bullet list of expectations
- Products are reloaded according to history.

**Comment by ah-net** [comment]
The fix for the price slider seems to fix this issue.
