### ISSUE TITLE
Error op de PLP

### ISSUE THREAD

**Issue by LarsRezelman** [EmicoEcommerce/Magento2Tweakwise-archived#25]
Bij het opzoeken van de PLP is ons in sommige gevallen, wanneer exact is ons niet duidelijk, is er een error. Onderstaande de error die wij tegen gekomen.

Environment
--
- [ ] PHP Version: (|7.0|)
- [ ] Magento Version 2.0.10:
- [ ] Magento Enterprise: (yes)
- [ ] Tweakwise Version: 0.3.0
- [ ] Magento Deploy Mode: (production|)

`a:4:{i:0;s:13:"Illegal state";i:1;s:4001:"#0 /var/www/vhosts/score/httpdocs/vendor/emico/tweakwise/src/Block/Catalog/Product/ProductList/Featured.php(86): Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection->addFieldToFilter('entity_id', Array)
#1 /var/www/vhosts/score/httpdocs/vendor/magento/module-catalog/Block/Product/ListProduct.php(321): Emico\Tweakwise\Block\Catalog\Product\ProductList\Featured->_getProductCollection()
#2 /var/www/vhosts/score/httpdocs/vendor/magento/module-page-cache/Model/Layout/LayoutPlugin.php(71): Magento\Catalog\Block\Product\ListProduct->getIdentities()
#3 /var/www/vhosts/score/httpdocs/vendor/magento/framework/Interception/Interceptor.php(152): Magento\PageCache\Model\Layout\LayoutPlugin->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), ' <script>\n    t...')
#4 /var/www/vhosts/score/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#5 /var/www/vhosts/score/httpdocs/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#6 /var/www/vhosts/score/httpdocs/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#7 /var/www/vhosts/score/httpdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /var/www/vhosts/score/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#9 /var/www/vhosts/score/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#10 /var/www/vhosts/score/httpdocs/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#11 /var/www/vhosts/score/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#12 /var/www/vhosts/score/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#13 /var/www/vhosts/score/httpdocs/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#14 /var/www/vhosts/score/httpdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#15 /var/www/vhosts/score/httpdocs/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)`

**Comment by Fgruntjes** [comment]
Hello Lars,

For our fellow Github users please try to keep the issues and communication in English. This way other people who might not speak our language with the same issue might benefit from it.

This is not an issue we can help you with, we would really need more information.

Please follow the issue template by providing steps to reproduce from a clean Magento installation with test data.

Kind regards,
Freek

**Comment by basselalaraaj** [comment]
@LarsRezelman @Fgruntjes 
duplicate of #21
