### ISSUE TITLE
Search redirects defined in navigator account are not working properly

### ISSUE THREAD

**Issue by VesnaS** [EmicoEcommerce/Magento2Tweakwise-archived#26]
Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.6
* Tweakwise Version: latest release
* Tweakwise Export Version: latest release
* Magento Deploy Mode: production
* Third party modules: yes

Steps to reproduce
--
1. Create redirect in Tweakwise navigator account

![redirect](https://user-images.githubusercontent.com/33281361/33729503-2e928d96-db7e-11e7-9750-b54014e02720.png)

2. Publish data and search for that term in Magento 

Actual result
--
We always get redirected to the home page

Expected result
--
Magento should redirect to defined URL

**Comment by EduardSelles** [comment]
Hello,

I think it will work if you select a store view as category instead of the 'root'. 

![image](https://user-images.githubusercontent.com/26865971/33934297-cb28278c-dff8-11e7-8ccc-1be2834aa686.png)

**Comment by VesnaS** [comment]
Hello,

I tried to change the configuration as you suggested, but to no avail.
The result is the same.

**Comment by EduardSelles** [comment]
Unfortunately we can not reproduce the problem in our two (CE & EE) demo environments. 

Maybe you can try to adjust the url again to a full path including 'http://'? 

I am afraid that Emico can not solve the problem if it is not reproducible in a clean Magento installation.

**Comment by VesnaS** [comment]
Hello Eduard,

Thank you for your reply.

Yes, setting redirects as full path with protocol and domain solved the issue.
I also tried clean Magento installation, and paths beginning with "/" also don't work - because of the issue that Magento UrlInterface has in the getUrl method that you used in your extension.

In conclusion, only full paths or relative paths (without beginning "/") will work properly.

Maybe you should consider looking into this issue in some future release.

**Comment by Fgruntjes** [comment]
If request by TW we will add support for full paths without domain in a feature release. Thank you for your test work on this.
