### ISSUE TITLE
Display of upsell and cross-sell on product in multiple categories

### ISSUE THREAD

**Issue by VesnaS** [EmicoEcommerce/Magento2Tweakwise-archived#27]
Hello, this issue is more of a question than a bug. We have products that are associated to multiple categories and it is not clear which one of them is used to determine cross-sell and upsell templates for product.

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.6
* Tweakwise Version: latest release
* Tweakwise Export Version: latest release
* Magento Deploy Mode: production
* Third party modules: yes

Steps to reproduce
--
1. In Magento, under Stores -> Configuration -> CATALOG -> Tweakwise -> Recommendations, enable Upsell and Cross-sell options, but don't choose default templates.
2. Also, we don't select Tweakwise templates on product level.

Actual result
--
1. Upsell and cross-sell are displayed on product in frontend

I assume they are collected from the category that the product belongs to. But this product is associated to over 10 categories, so which one is used to determine Tweakwise templates?

**Comment by Fgruntjes** [comment]
we use the current category set by Magento. So this depends trough which url the product was opened.

If the product was requested with a direct product url without category then the no category is used. This is consistent with the breadcrumb functionality of Magento. 

If you wish to also use a category template when the product was requested directly you should set the 'current_category' registry key in an observer.

Kind regards,
Freek
