### ISSUE TITLE
Product list "Sort by" option resets selected option after return to the first page in pagination

### ISSUE THREAD

**Issue by VesnaS** [EmicoEcommerce/Magento2Tweakwise-archived#30]
Environment
--
* PHP Version: 7.0
* Magento Version: upgraded to 2.2.2
* Tweakwise Version: 1.0.8
* Tweakwise Export Version: 1.1.1
* Magento Deploy Mode: production & development
* Third party modules: yes

Steps to reproduce
--
1. Create few "Sorting options" in Tweakwise navigator account
2. Create "Sorting template" and associate created sorting options to it
![sorting_options](https://user-images.githubusercontent.com/33281361/34947039-344dce18-fa09-11e7-87e9-77fbf94e81da.png)
3. Associate created template to one of the categories, and publish data

Expected result
--
- When I sort product list on frontend, it works as expected
![levertijd_sorting](https://user-images.githubusercontent.com/33281361/34947434-62ff1c16-fa0a-11e7-96bc-c6586e616204.png)

- If I use pagination, it also keeps selected sorting option, and this is url query
```
?p=2&product_list_order=Levertijd
```
Actual result
--
1. The problem occurs when I go back to the first page in pagination - sorting option resets to the default value, as if it was never selected, but url query remains. If I then try to select new sorting option, this is what I end up with in url query
```
?&product_list_order=Levertijd&product_list_order=Final+price+ascending
```

**Comment by Fgruntjes** [comment]
Hello,

We tested the issue on our demo environment: https://tweakwise2-ce.emico.nl/women/tops-women.html but could not reproduce with default theme. Also see video: http://nimb.ws/LuPH18. 

If you can provide the steps to reproduce the issue on a fresh install please do then i'll reopen the issue.

Kind regards
Freek
