### ISSUE TITLE
Wrong outline product title in autocomplete

### ISSUE THREAD

**Issue by joost-florijn-kega** [EmicoEcommerce/Magento2Tweakwise-archived#32]
Issue Brief
--
The product title in the autocomplete doesn't use the full width

Environment
--
* PHP Version: (5.6|7.0|7.1)
* Magento Version: 2.1.9
* Tweakwise Version: 1.0.9
* Tweakwise Export Version: 1.1.2
* Magento Deploy Mode: production|development

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Search and look at the outlining of the product title in the autocomplete.

Actual result
--
1. 
![actual_result](https://user-images.githubusercontent.com/16535591/35679396-29811688-0757-11e8-95c3-7a0fa55220c4.png)

Expected result
--
1. 
![expected_result](https://user-images.githubusercontent.com/16535591/35679401-30aaf3e8-0757-11e8-9a6b-c47e20c66fc8.png)

**Comment by Fgruntjes** [comment]
Thank you for your merge request. We have verified and merged your changes.
