### ISSUE TITLE
Wrong message is shown on the search result page when no products are found

### ISSUE THREAD

**Issue by joost-florijn-kega** [EmicoEcommerce/Magento2Tweakwise-archived#34]
Issue Brief
--
When you search on a search term that results in no products are found the wrong message is shown.

Environment
--
* PHP Version: (5.6|7.0|7.1)
* Magento Version: 2.1.9
* Tweakwise Version: 1.0.9
* Tweakwise Export Version: 1.1.2
* Magento Deploy Mode: production|development

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Search on a term that you now results in zero products.

Actual result
--
1. The message 'We can't find products matching the selection.' is shown.

Expected result
--
List the expected results as a bullet list of expectations
- [ ] The following message should be shown: 'Your search returned no results.'

The reason why the wrong message is shown is because the result block of Magento checks if there are any results with the function 'getSize()':
https://github.com/magento/magento2/blob/2.1/app/code/Magento/CatalogSearch/Block/Result.php#L203

The function getSize uses the getSelectCountSql function to check how many products are found (https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php#L217). The product collection hasn't been filtered yet because that happens on load.

**Comment by Fgruntjes** [comment]
Thank you for your merge request, we have verified and merged your changes.
