### ISSUE TITLE
Feature request: add setting for adding visibility as filter parameter

### ISSUE THREAD

**Issue by arnoudhgz** [EmicoEcommerce/Magento2Tweakwise-archived#36]
In Magento you can set a product visibility to 'Not individually', 'Catalog', 'Search', 'Catalog, Search'.
It would be nice if this attribute can be selected in the setting as a filter option.

In the export module you can choose already which visibility you want to export, but I would like to be able to export all products and just use a visibility filter as search parameter.

**Comment by Fgruntjes** [comment]
Moved to correct project https://github.com/EmicoEcommerce/Magento2TweakwiseExport/issues/39
