### ISSUE TITLE
Visibility filter missing

### ISSUE THREAD

**Issue by jasperzeinstra** [EmicoEcommerce/Magento2Tweakwise-archived#40]
Issue Brief
--
Magento has the attribute `visibility`, but the extension doesn't do anything with this feature. What would like to see is the following. For all the API requests to Tweakwise we would like the extension to always add the attribute `visibility` as an active filter `tn_fk_visibility=\Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH`. If the request is for search we would like to also have the filter `tn_fk_visibility=\Magento\Catalog\Model\Product\Visibility::VISIBILITY_IN_SEARCH` and for all other requests it would be `tn_fk_visibility=\Magento\Catalog\Model\Product\Visibility::VISIBILITY_IN_CATALOG`. When this is added to the API request we can add the attribute `visibility` to our filter template in the Tweakwise Navigator backend. We'll set it to `checkbox` and `hidden`. Now on category pages only the products will be shown that are either visible in both catalog and search or only in catalog. And during a search request only products with visibility both or search will be visible. When someone doesn't add the attribute `visibility` to tweakwise filter template in navigator products with every visibility will be shown.

Environment
--
* PHP Version: (7.0)
* Magento Version: Magento 2.2.3
* Tweakwise Version: 1.1.0
* Tweakwise Export Version: -
* Magento Deploy Mode: production
* Third party modules: -

Steps to reproduce
--
1. Install Magento from `1.1.0` tag.
2. Create a product and set visibility to `search` and connect to a category
3. Create a product and set visibility to `catalog` and connect to a category
4. Visit the category and see if product with visibility `search` isn't shown
5. Search for the product with visibility `catalog` and see if product isn't shown.

Actual result
--
* Products with visibility `search` is also visible in category
* Products with visibility `catalog` is also visible in search

Expected result
--
- [ ] Products with visibility `search` shouldn't be visible in a category
- [ ] Products with visibility `catalog` shouldn't be visible during search
- [ ] Products with visibility `catalog, search` should be visible in categories and search.

**Comment by Fgruntjes** [comment]
Thank you for your clarification, we agree that this is a bug to be resolved. As written with the merge request #41 that would break certain current use cases.

We are working on a different way of solving this issue. Unfortunately filteren the autocomplete suggestions is not possible. In this case you should disable the product suggestions completely or accept that there will be less products in the suggestion as expected.

**Comment by Fgruntjes** [comment]
Just a small reminder for myself.

With the current changes the catalog query will be filtered based on the correct visibility in search / catalog. However the query to Tweakwise is not changed yet. This still needs to be done but only if the `Emico\Tweakwise\Model\Config::getLayeredFilterVisibility()` or for the search requests `Emico\Tweakwise\Model\Config::getSearchFilterVisibility()` is enabled.

Also filtering for auto complete can only be done on the Magento side since Tweakwise does not support filtering this result based on attributes.

**Comment by edwinljacobs** [comment]
This has been fixed in the latest version. see tag v1.4.3 and its release notes.

With kind regards

**Comment by EduardSelles** [comment]
@jasperzeinstra Hi Jasper. Since this issue is solved, can you close it? Thank you in advance.
