### ISSUE TITLE
When authentication_key is empty, the frontend crashes

### ISSUE THREAD

**Issue by hostep** [EmicoEcommerce/Magento2Tweakwise-archived#46]
Issue Brief
--
We have an environment where we don't have the authentication_key filled in for the Tweakwise module. But doing this crashes the frontend with the error:

```
1 exception(s):
Exception #0 (Emico\Tweakwise\Exception\ApiException): Invalid response received by Tweakwise server, response code is not 200. Request "http://navigator-group1.tweakwise.com/navigation/?tn_ps=24"
```

Environment
--
* PHP Version: 7.0.27
* Magento Version: EE 2.2.2
* Tweakwise Version: v1.3.2
* Tweakwise Export Version: v1.1.4
* Magento Deploy Mode: production & development (both)
* Third party modules: all kinds

Steps to reproduce
--
1. In the database, make sure the config value `tweakwise/general/authentication_key` contains an empty string (or an invalid key)
2. Visit a page which uses Tweakwise (in our case the homepage)

Actual result
--
```
1 exception(s):
Exception #0 (Emico\Tweakwise\Exception\ApiException): Invalid response received by Tweakwise server, response code is not 200. Request "http://navigator-group1.tweakwise.com/navigation/?tn_ps=24"
```

Expected result
--
Tweakwise acts like it is disabled and doesn't crash

**Comment by hostep** [comment]
We can work around this by setting the Enabled flag in the Layered Navigation section of the Tweakwise configuration in Magento to No.

If you think that this is correct behaviour, you may close this issue :)

**Comment by EduardSelles** [comment]
@hostep Thanks for mentioning the solution for this question ;-) Yes, we think this is the correct behaviour. Can you close this issue? Because I can't.

**Comment by hostep** [comment]
Sure :)
