### ISSUE TITLE
Price fillter always applied when slider

### ISSUE THREAD

**Issue by Echron** [EmicoEcommerce/Magento2Tweakwise-archived#56]
Issue Brief
--
When applying a filter (for example brand) to the categorie overview the final_price filter is also applied (without pushing "apply" on that filter). The price is shown as a slider, when changing the view to checkboxes this issue doesn't occure.

Environment
--
* PHP Version: PHP 7.0.31
* Magento Version: Magento2 Commerce 2.2.5
* Tweakwise Version: v1.4.2
* Tweakwise Export Version: v1.2.3
* Magento Deploy Mode: (production|development) both
* Third party modules:

Steps to reproduce
--
1. Add the price filter as a slider to the filter options and make sure you have other filters on attributes
2. Apply a filter on onother attribute

Actual result
--
1. Besides the expected filter, the price filter is also applied

Expected result
--
Only the applied filter should be used

**Comment by EduardSelles** [comment]
@Echron We cannot reproduce this issue in our test environment.
Check: https://tweakwise2-ce.emico.nl/women/tops-women.html

Selecting the size 'XS' gives the next url:
https://tweakwise2-ce.emico.nl/women/tops-women.html?size%5B0%5D=XS

I suppose this is okay. 
Can you give a specific example where it goes wrong?

**Comment by edwinljacobs** [comment]
CLosed due to inactivity
