### ISSUE TITLE
Headers already send when trying to retrieve generated feed xml

### ISSUE THREAD

**Issue by igorwulff** [EmicoEcommerce/Magento2Tweakwise-archived#73]
Issue Brief
--
In the following class vendor/magento/module-page-cache/Model/App/Response/HttpPlugin.php and X-Vary cookie can potentially be triggered unless the empty interface \Magento\Framework\App\PageCache\NotCacheableInterface is used. This causes the error 'headers already sent' to be shown on the screen along with an invalid xml feed. Since the text is already inserted in the output when calling the execute method for Emico\TweakwiseExport\App\Response. The actual xml feed is still valid, but can now not be imported from the Navigator, because of this.

The FileStorage Response class is using this: vendor/magento/module-media-storage/Model/File/Storage/Response.php. We could perhaps use this class or create our own Result class with this interface to fix the problem with setting the x-vary cookie after outputting the feed.

**Problem:** The Export execute method is not using a valid response object based on the interface: \Magento\Framework\Controller\ResultInterface|ResponseInterface But instead renders the feed to an output stream. 

**Way to go:** We should either use an Result object which also implements \Magento\Framework\App\PageCache\NotCacheableInterface to avoid the X-Vary Cookie being set or place a die/exit at the end of the execute method.

The last solution is ugly, but might be good as a temporary fix. The first proposed solution would be the ideal way to go in my opinion.

Environment
--
* PHP Version: (7.2)
* Magento Version: 2.3.1
* Tweakwise Version: v1.4.9
* Tweakwise Export Version: v1.3.4
* Magento Deploy Mode: (production)
Steps to reproduce
--
I'm unsure how to reproduce this exactly. The problem occurs because a X-Vary / Sensitive Cookie is set after the Emico export action is done. The issue occurs because of the following:

Actual result
Headers already sent

Expected result
Outputted xml file

**Comment by niekv** [comment]
I can confirm this issue for one of our clients.

- Magento version: v2.2.8
- Tweakwise Version: v1.4.9
- Tweakwise Export Version: v1.3.4
- Deploy mode: developer

**Comment by edwinljacobs** [comment]
Hi,

I added a possible fix for this issue. https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/70

We decided not to extend the Action class (this is not needed) and return an instance of the filestorage class as suggested. To be honest i am unsure if there exists a "cleaner" solution. Perhaps you can give me some feedback on that pull en test if this fixes the issue?

With kind regards

**Comment by niekv** [comment]
I can confirm the PR fixed the issue for our client.

**Comment by edwinljacobs** [comment]
Nice to hear,

This will be released at the next opportunity.

With kind regards

**Comment by niekv** [comment]
Great, thanks.

**Comment by edwinljacobs** [comment]
The fix  has been released in https://github.com/EmicoEcommerce/Magento2TweakwiseExport/releases/tag/v1.3.6

With kind regards
