### ISSUE TITLE
Tweakwise not working with Magento 2.3 when ElasticSearch modules are enabled

### ISSUE THREAD

**Issue by jasperzeinstra** [EmicoEcommerce/Magento2Tweakwise-archived#79]
I just wanted to let you know that Tweakwise isn't working when the modules for ElasticSearch are enabled. Would be nice if you would get some kind of warning if one of these modules is enabled. You should disable them in `app/etc/config.php`.

Regards,
Jasper

**Comment by edwinljacobs** [comment]
Ok thanks for your report.

We will look into it

**Comment by edwinljacobs** [comment]
Hi I have updated https://github.com/EmicoEcommerce/Magento2Tweakwise/issues/80 with an explanation of why this is the case. Most likely we will add the required entries in di.xml so that Tweakwise keeps working.

With kind regards

**Comment by edwinljacobs** [comment]
Hi, We released a fix for issue #80 

Does that sufficiently solve this issue?

With kind regards

**Comment by edwinljacobs** [comment]
Closed due to inactivity
