### ISSUE TITLE
Product Empty When Page Exceed

### ISSUE THREAD

**Issue by binohartoko** [EmicoEcommerce/Magento2Tweakwise-archived#8]
In the category page, product list is empty when a page is exceed the total page. Even this is logically correct but this can be confusing for customer. And also this behavior is different from default Magento.

When page is exceed the total page, it should be corrected by go to the last page

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.7
* Tweakwise Version: 1.0.1
* Tweakwise Export Version: 1.0.2
* Magento Deploy Mode: production

Steps to reproduce
--
1. Go to a category page with pagination in it (has multiple pages)
2. Make sure the page size option is not the biggest
3. Go to the last page
4. Set the page size option bigger

Actual result
--
- Page has product list empty

Expected result
--
List the expected results as a bullet list of expectations
- Like default Magento, it's corrected by go to the last page of it's page size

**Comment by Fgruntjes** [comment]
We solved this with triggering a 302 redirect, this is a bit cleaner then original magento where you would theoretically create duplicated content.
