### ISSUE TITLE
Client.php throws exeption if there are multiple values per attribute

### ISSUE THREAD

**Issue by CyberSecutor** [EmicoEcommerce/Magento2Tweakwise-archived#86]
Issue Brief
--
An exception is thrown when an item has multiple values per attribute.

Environment
--
* PHP Version: 7.2
* Magento Version: 2.3.2
* Tweakwise Version: 2.0.1
* Tweakwise Export Version: n.a.
* Magento Deploy Mode: production & development
* Third party modules:

Steps to reproduce
--
Given the following response from Tweakwise:
```xml
  <items>
    <item>
      <itemno>1001</itemno>
      <title>My Item</title>
      <price>5.95</price>
      <brand />
      <attributes>
        <attribute>
          <name>sku</name>
          <values>
            <value>315880</value>
            <value>315930</value>
            <value>315950</value>
            <value>315990</value>
            <value>352010</value>
            <value>399570</value>
            <value>399590</value>
            <value>416510</value>
            <value>437570</value>
            <value>437580</value>
          </values>
        </attribute>
      </attributes>
    </item>
  <items>
```
The Emico\Tweakwise\Model\Client class will throw an exception when trying to convert it to array in `xmlToArray()`.

Expected result
--
- [ ] Parse the XML without throwing an exception.

Patch
--
I have created a patch that fixes the issue:
https://bitbucket.org/snippets/remkoMCT/qng5be

**Comment by edwinljacobs** [comment]
Sorry for the rather late reply, I havent got around to looking into this yet. We will reproduce this issue and test the patch against it. 

With kind regards

**Comment by edwinljacobs** [comment]
Hello,

This has been fixed in https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v2.1.4 and is no longer an issue. I will close this issue.

With kind regards
