### ISSUE TITLE
Fatal error when updating Tweakwise to >2.1.0 on Layered Navigation

### ISSUE THREAD

**Issue by igorwulff** [EmicoEcommerce/Magento2Tweakwise-archived#95]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 7.2
* Magento Version: 2.3.2-p2
* Tweakwise Version: anything between v2.1.2-v2.1.4
* Magento Deploy Mode: production
* Third party modules:

Steps to reproduce
--
1. Upgrade Tweakwise to v2.1.2-v2.1.4

Actual result
1. [Example] Error message appears:
2019/12/18 15:46:30 [error] 13441#13441: *53432 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Swatches\Helper\Data::isSwatchAttribute() must be an instance of Magento\Catalog\Model\ResourceModel\Eav\Attribute, instance of Magento\Catalog\Model\Entity\Attribute given, called in /vendor/magento/module-swatches/Model/Plugin/FilterRenderer.php on line 56 and defined in /vendor/magento/module-swatches/Helper/Data.php:560
Stack trace:
#0 /vendor/magento/module-swatches/Model/Plugin/FilterRenderer.php(56): Magento\Swatches\Helper\Data->isSwatchAttribute(Object(Magento\Catalog\Model\Entity\Attribute))
#1 /vendor/magento/framework/Interception/Interceptor.php" while reading response header from upstream, client: {{ip}}, server: , request: "GET /catalog/category/view/s/anti-pluis-shampoo/id/2163/ HTTP/1.1", upstream: "", host: "{{host}}", referrer: "https://{{host}}/catalog/category/view/s/shampoo-op-producttype/id/442/"

**Comment by igorwulff** [comment]
The following patch seems to fix the issue. We will continue to test this:
`--- a/vendor/emico/tweakwise/src/Model/Catalog/Layer/FilterList/Tweakwise.php	2019-12-19 09:31:48.608140870 +0100
+++ b/vendor/emico/tweakwise/src/Model/Catalog/Layer/FilterList/Tweakwise.php	2019-12-19 09:30:05.482000000 +0100
@@ -14,7 +14,7 @@
 use Emico\Tweakwise\Model\Config;
 use Magento\Catalog\Model\Layer;
 use Magento\Catalog\Model\Layer\Filter\FilterInterface;
-use Magento\Catalog\Model\Entity\AttributeFactory;
+use Magento\Catalog\Model\ResourceModel\Eav\AttributeFactory;
 use Magento\Eav\Model\Entity\Attribute;
 use Emico\Tweakwise\Model\Client\Type\FacetType;
 
`

**Comment by igorwulff** [comment]
I can confirm that the above path has resolved our issues for later version of Tweakwise. Can you see if you can merge this into the codebase?

**Comment by edwinljacobs** [comment]
Hi,

Thanks for reporting, ill verify this issue and check why it does not apply on my installations.

**Comment by edwinljacobs** [comment]
Hi,

Just to check: In your configuration do you have "Use default magento filter renderer" set to true?
If this is the case then the swatch renderer plugin triggers and indeed there is a type error. What I dont get, but thats problably just me, is that method:
```php
/**
     * Check if an attribute is Swatch
     *
     * @param Attribute $attribute
     * @return bool
     */
    public function isSwatchAttribute(Attribute $attribute)
    {
        return $this->swatchTypeChecker->isSwatchAttribute($attribute);
    }
```
Takes a ```Magento\Catalog\Model\ResourceModel\Eav\Attribute``` but the method its passing the attribute argument to, namely ```$this->swatchTypeChecker->isSwatchAttribute($attribute) ``` takes an AttritbuteInterface .... which indicates that the method definition is incorrect .... Nevertheless it is indeed broken. The reason we choose ```Magento\Catalog\Model\Entity\AttributeFactory``` is that method 
```php
/**
     * Set attribute model to filter
     *
     * @param   \Magento\Eav\Model\Entity\Attribute $attribute
     * @return  \Magento\Catalog\Model\Layer\Filter\AbstractFilter
     */
    public function setAttributeModel($attribute)
    {
        $this->setRequestVar($attribute->getAttributeCode());
        $this->setData('attribute_model', $attribute);
        return $this;
    }
```

in class ```Magento\Catalog\Model\Layer\Filter\AbstractFilter``` takes a ```\Magento\Eav\Model\Entity\Attribute``` and not some resourcemodel. After looking at this again we find that method 

```php
/**
     * Get attribute model associated with filter
     *
     * @return \Magento\Catalog\Model\ResourceModel\Eav\Attribute
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function getAttributeModel()
    {
        $attribute = $this->getData('attribute_model');
        if ($attribute === null) {
            throw new \Magento\Framework\Exception\LocalizedException(__('The attribute model is not defined.'));
        }
        return $attribute;
    }
``` 
in the abstract filter class returns a resourcemodel, so again inconsistent :(
We must have missed that and also did not check the case for the default filter renderer.

You can make a pull request if you like, if not then ill fix it.

With kind regards

**Comment by edwinljacobs** [comment]
Hi, 

This has been fixed in https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v2.1.5

With kind regards
