### ISSUE TITLE
Magento 2.2.X compatibility

### ISSUE THREAD

**Issue by jeroenkosse** [EmicoEcommerce/Magento2Tweakwise-archived#96]
Issue Brief
--
Latest version of Magento2Tweakwise not compatible with Magento 2.2.x

Environment
--
* PHP Version: 7.2
* Magento Version: 2.2.5
* Tweakwise Version: 2.1.4
* Tweakwise Export Version: 1.5
* Magento Deploy Mode: production|development
* Third party modules:

Steps to reproduce
--
1. Run the setup di compile command for production mode or in development mode.

Actual result
--
1. Error for the return types for specific interfaces in tweakwise and in the export module. The Auto Generated Proxy classes do not support the return types in magento 2.2.x
2. A missing InventoryApi module that is a Dependency in the Tweakwise Export module. This InventoryApi extension is build specifically for magento >= 2.3 aand magento 2.3 is not a requirement for this module to install.

Expected result
--
List the expected results as a bullet list of expectations
- No errors when the setup di compile is finished

**Comment by edwinljacobs** [comment]
Moved to: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/issues/80
Closing this issue as it should be reported in the export module.
