### ISSUE TITLE
Maximum price rounded down in price filter (slider)

### ISSUE THREAD

**Issue by KoenWouters** [EmicoEcommerce/Magento2Tweakwise-archived#99]
Issue Brief
--
When a product has a decimal price like "89.95" the maximum value is not correct because they are rounded down to "89" in the price slider. 

Environment
--
* PHP Version: 7.1
* Magento Version: 2.2.10
* Tweakwise Version: 2.1.2
* Tweakwise Export Version: 1.5.0
* Magento Deploy Mode: development

Steps to reproduce
--
1. Add a product with a decimal price
2. Search for the product and see the price slider has a price lower as the price of the product as maximum value.

Actual result
--
![product](https://user-images.githubusercontent.com/7394260/73177968-9b5bfa80-4110-11ea-9258-7d63c4e3be7e.jpg)

Expected result
--
- Price slider for given screenshot above should be 89(min) - 90(max)

**Comment by edwinljacobs** [comment]
Hi,

Problably just a rounding / casting error. We will look into it.

With kind regards

**Comment by edwinljacobs** [comment]
Hello,

We added branch issue/99-price-rounding-error-slider to fix this issue.
The slider block code has been simplified (at the cost of removing one public function which is unfortunate) Can you verify if this fixes your issue?

With kind regards

**Comment by KoenWouters** [comment]
Hi,

Looks like this is working as expected!

**Comment by edwinljacobs** [comment]
Ok, nice to hear!

We will add this to our next release.

With kind regards

**Comment by edwinljacobs** [comment]
Hello,

Release https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v2.1.8 should take care of this issue. I decided to keep the previously removed public methods so that existing installations can upgrade safely. These methods will be removed in the next major release.

With kind regards
